name: Python Hello World

on:
  push:
    branches:
      - python-hello-world

jobs:
  python-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Python script
        run: python hello.py
